-- luacheck configuration for Auctionator WoW addon (WoW 3.3.5 / Lua 5.1)
-- Run with:  luacheck Auctionator/

std = "lua51"

max_line_length = false

globals = {
    -- WoW addon system
    "SlashCmdList",
    "SLASH_AUCTIONATOR1", "SLASH_AUCTIONATOR2",

    -- WoW API – auction house
    "AuctionFrame", "AuctionFrameBrowse", "BrowseSearchButton",
    "BrowseResetButton", "BrowseNameText", "BrowseMinLevel",
    "BrowseMaxLevel", "BrowseDropDown", "BrowseIsUsable",
    "AuctionFrameTab1", "AuctionFrameTab2", "AuctionFrameTab3",
    "GetAuctionItemInfo", "GetAuctionItemLink", "GetNumAuctionItems",
    "PlaceAuctionBid", "StartAuction", "CanSendAuctionQuery",
    "QueryAuctionItems", "CancelAuction", "GetAuctionItemTimeLeft",

    -- WoW API – items / inventory
    "GetItemInfo", "GetItemQualityColor", "GetContainerNumSlots",
    "GetContainerItemInfo", "GetContainerItemLink", "GetContainerNumFreeSlots",
    "PickupContainerItem", "PutItemInBag", "CursorHasItem",
    "GetInventoryItemInfo", "GetInventoryItemLink",
    "GetSellValue", "GetAuctionBuyout", "GetMerchantItemInfo",
    "GetDisenchantItemInfo",

    -- WoW API – money / prices
    "GetMoney", "MoneyFrame_Update",

    -- WoW API – UI / frames
    "UIParent", "ChatFrame1", "DEFAULT_CHAT_FRAME",
    "GameFontNormalSmall", "GameFontNormal", "GameFontHighlight",
    "CreateFrame", "StaticPopup_Show", "StaticPopupDialogs",
    "InterfaceOptions_AddCategory", "InterfaceOptionsFrame",
    "InterfaceOptionsFramePanelContainer", "InterfaceOptionsListScrollFrame",
    "GameTooltip", "GameTooltip_SetDefaultAnchor",
    "FauxScrollFrame_Update", "FauxScrollFrame_GetOffset",
    "FauxScrollFrame_SetOffset", "FauxScrollFrame_OnMouseWheel",
    "FauxScrollFrame_OnVerticalScroll",
    "UIDropDownMenu_Initialize", "UIDropDownMenu_AddButton",
    "UIDropDownMenu_SetSelectedID", "UIDropDownMenu_SetSelectedName",
    "UIDropDownMenu_GetSelectedID",

    -- WoW API – events / system
    "RegisterAddonMessagePrefix", "SendAddonMessage",
    "IsShiftKeyDown", "IsAltKeyDown", "IsControlKeyDown",
    "UnitName", "GetRealmName",
    "time", "date", "format", "gsub", "strsplit", "strjoin",
    "bit",

    -- Auctionator globals defined across multiple files
    "Auctionator", "AuctionatorVersion", "AuctionatorAuthor",
    "Atr_IsDev",
    "AUCTIONATOR_SAVEDVARS", "AUCTIONATOR_PRICING_HISTORY",
    "AUCTIONATOR_SHOPPING_LISTS", "AUCTIONATOR_PRICE_DATABASE",
    "AUCTIONATOR_MEAN_PRICE_DATABASE", "AUCTIONATOR_LAST_SCAN_TIME",
    "AUCTIONATOR_TOONS", "AUCTIONATOR_STACKING_PREFS",
    "AUCTIONATOR_SCAN_MINLEVEL",
    "AUCTIONATOR_SHOW_ST_PRICE", "AUCTIONATOR_ENABLE_ALT",
    "AUCTIONATOR_OPEN_FIRST", "AUCTIONATOR_OPEN_BUY",
    "AUCTIONATOR_OPEN_ALL_BAGS", "AUCTIONATOR_DEF_DURATION",
    "AUCTIONATOR_SHOW_TIPS", "AUCTIONATOR_V_TIPS", "AUCTIONATOR_A_TIPS",
    "AUCTIONATOR_D_TIPS", "AUCTIONATOR_SHIFT_TIPS",
    "AUCTIONATOR_DE_DETAILS_TIPS", "AUCTIONATOR_DEFTAB",
    "AtrQuery", "Atr_NewQuery",
    "Atr_GetSellValue", "Atr_GetAuctionBuyout", "Atr_GetAuctionPrice",
    "Atr_GetDisenchantValue", "Atr_CalcDisenchantPrice",
    "ZF", "gAtrZC",
    "GetSellValue", "GetAuctionBuyout",

    -- Additional WoW API globals
    "ACCEPT",
    "ATR_FSS_NULL", "ATR_FS_ANALYZING", "ATR_FS_CLEANING_UP",
    "ATR_FS_NULL", "ATR_FS_STARTED",
    "ATR_SHOW_CURRENT", "ATR_SHOW_HINTS", "ATR_SHOW_HISTORY",
    "ATR_SK_FLASKS", "ATR_SK_GEMS_CUT", "ATR_SK_GEMS_UNCUT",
    "ATR_SK_GLYPHS", "ATR_SK_HERBS", "ATR_SK_ITEM_ENH", "ATR_SK_POT_ELIX",
    "ATR_tipsAuctionOpt_CB", "ATR_tipsDisenchantOpt_CB", "ATR_tipsVendorOpt_CB",
    "AtrBuildLTable_enUS", "AtrBuildLTable_esES", "AtrBuildLTable_ruRU",
    "AtrL", "AtrPane", "AtrScan", "AtrScanningTooltip", "AtrSearch",
    "Atr_ASDD_Class", "Atr_ASDD_Class_Initialize", "Atr_ASDD_Class_OnClick",
    "Atr_ASDD_Class_OnLoad", "Atr_ASDD_Subclass", "Atr_ASDD_Subclass_Initialize",
    "Atr_ASDD_Subclass_OnLoad", "Atr_ASDD_UpdateSubclassMenu",
    "Atr_AS_Maxlevel", "Atr_AS_Minlevel", "Atr_AS_Searchtext",
    "Atr_AbbrevItemName", "Atr_AddMenuPick", "Atr_AddToItemLinkCache",
    "Atr_AddToLowPrices", "Atr_AddToSListButton", "Atr_AddToSListOnClick",
    "Atr_Adv_Search_Button", "Atr_Adv_Search_Dialog", "Atr_Adv_Search_Do",
    "Atr_Adv_Search_Onclick", "Atr_Adv_Search_Reset",
    "Atr_Back_Button", "Atr_BasicOptionsFrame_BTitle", "Atr_BasicOptionsFrame_Save",
    "Atr_BuildHints",
    "Atr_Buy1_Button", "Atr_Buy1_Onclick", "Atr_Buy_BuildMatchList",
    "Atr_Buy_BuyNextOnPage", "Atr_Buy_Cancel", "Atr_Buy_ClearMatchList",
    "Atr_Buy_Confirm_CancelBut", "Atr_Buy_Confirm_Frame", "Atr_Buy_Confirm_ItemName",
    "Atr_Buy_Confirm_Max_Text", "Atr_Buy_Confirm_Numstacks", "Atr_Buy_Confirm_OK",
    "Atr_Buy_Confirm_OKBut", "Atr_Buy_Confirm_Text2", "Atr_Buy_Confirm_Update",
    "Atr_Buy_Continue_Text", "Atr_Buy_Debug1", "Atr_Buy_Idle", "Atr_Buy_IsComplete",
    "Atr_Buy_IsFirstPassComplete", "Atr_Buy_NextPage_Or_Cancel",
    "Atr_Buy_NumAvail_Text", "Atr_Buy_OnAuctionUpdate", "Atr_Buy_PageHasMatch",
    "Atr_Buy_Part1", "Atr_Buy_QueueQuery", "Atr_Buy_SendQuery",
    "Atr_CalcNewDBprice", "Atr_CheckForBargain", "Atr_Check_For_Conflicts",
    "Atr_ClearAll", "Atr_ClearBrowseListings", "Atr_ClearBuyState",
    "Atr_ClearScanCache", "Atr_Clear_StackingPrefs",
    "Atr_Col1_Heading", "Atr_Col1_Heading_ButtonArrow", "Atr_Col3_Heading",
    "Atr_Col3_Heading_ButtonArrow", "Atr_Col4_Heading",
    "Atr_DEReqLevel", "Atr_DelSListButton", "Atr_DelSList_OnClick",
    "Atr_DisplaySlist", "Atr_DoesAuctionMatch",
    "Atr_DropDownSL", "Atr_DropDownSL_Initialize", "Atr_DropDownSL_OnClick",
    "Atr_DropDownSL_OnLoad", "Atr_Dropdown_AddPick", "Atr_DumpDETable",
    "Atr_Error_Display", "Atr_Error_Frame", "Atr_Error_Text",
    "Atr_FSR_added_count", "Atr_FSR_ignored_count", "Atr_FSR_scanned_count",
    "Atr_FSR_updated_count",
    "Atr_FindScan", "Atr_FindScanAndInit",
    "Atr_FullScanAnalyze", "Atr_FullScanDBsize", "Atr_FullScanDBwhen",
    "Atr_FullScanDone", "Atr_FullScanFrame", "Atr_FullScanFrameIdle",
    "Atr_FullScanHTML", "Atr_FullScanMoreDetails", "Atr_FullScanNext",
    "Atr_FullScanResults", "Atr_FullScanStart", "Atr_FullScanStartButton",
    "Atr_FullScanStatus", "Atr_FullScan_GetDurString",
    "Atr_GetAuctionClasses", "Atr_GetAuctionPriceDE", "Atr_GetAuctionSubclasses",
    "Atr_GetBonding", "Atr_GetCurrentPane", "Atr_GetDBsize", "Atr_GetItemLink",
    "Atr_GetMeanPrice", "Atr_GetMostRecentSale", "Atr_GetNextDustIntoCache",
    "Atr_HighlightEntry", "Atr_Hlist_ScrollFrame", "Atr_Hook_OnTooltipAddMoney",
    "Atr_InitDETable", "Atr_InitOptionsPanels",
    "Atr_IsArmorType", "Atr_IsClass", "Atr_IsCompoundSearch", "Atr_IsCutGem",
    "Atr_IsElixir", "Atr_IsFlask", "Atr_IsGem", "Atr_IsGlyph", "Atr_IsHerb",
    "Atr_IsItemEnhancement", "Atr_IsPotion", "Atr_IsTabSelected", "Atr_IsWeaponType",
    "Atr_ItemType2AuctionClass",
    "Atr_LoadOptionsSubPanel", "Atr_LocalizeFrames", "Atr_MakeOptionsFrameOpaque",
    "Atr_Mem_DD_numStacks", "Atr_Mem_EB_itemName", "Atr_Mem_EB_stackSize",
    "Atr_Mem_Forget", "Atr_Mem_itemName_static", "Atr_Mem_itemName_text",
    "Atr_Mem_stacksOf_text", "Atr_MemorizeFrame",
    "Atr_Memorize_Forget", "Atr_Memorize_Save", "Atr_Memorize_Show",
    "Atr_NewSearch", "Atr_NewSlist_OnClick",
    "Atr_Option_OnClick", "Atr_Options_Cancel",
    "Atr_ParseCompoundSearch", "Atr_PickLocalizationTable", "Atr_PrintBargains",
    "Atr_Process_Historydata",
    "Atr_RB_L", "Atr_RB_M", "Atr_RB_S",
    "Atr_RemFromSListButton", "Atr_RemFromSListOnClick", "Atr_ResetSavedVars",
    "Atr_SEntryOnClick", "Atr_SList",
    "Atr_SONumStacks_Initialize", "Atr_SONumStacks_OnClick", "Atr_SONumStacks_OnLoad",
    "Atr_ScanningOptionsFrame_Save",
    "Atr_Search_Box", "Atr_Search_Button", "Atr_Search_Onclick",
    "Atr_SetDurationOptionRB", "Atr_SetMFcolor", "Atr_SetMessage",
    "Atr_SetUINeedsUpdate",
    "Atr_Set_StackingPrefs_numstacks", "Atr_Set_StackingPrefs_stacksize",
    "Atr_SetupBasicOptionsFrame", "Atr_SetupOptionsFrame",
    "Atr_SetupScanningConfigFrame", "Atr_SetupStackingFrame",
    "Atr_SetupTooltipsOptionsFrame", "Atr_SetupUCConfigFrame",
    "Atr_Shop_OnFinishScan", "Atr_Shop_UpdateUI", "Atr_ShoppingListsInit",
    "Atr_ShowFullScanFrame", "Atr_ShowHide_StartingPrice", "Atr_ShowHints",
    "Atr_ShowOptionTooltip", "Atr_ShowingCurrentAuctions",
    "Atr_SortAuctionData", "Atr_SortSlists",
    "Atr_StackingEntry_OnClick", "Atr_StackingEntry_OnDoubleClick",
    "Atr_StackingList_Display", "Atr_StackingList_Edit_OnClick",
    "Atr_StackingList_New_OnClick",
    "Atr_StackingOptionsFrame_Edit", "Atr_StackingPrefs_Init",
    "Atr_Stacking_List", "Atr_Stacking_ScrollFrame",
    "Atr_Starting_Discount", "Atr_SubType2AuctionSubclass",
    "Atr_TooltipsOptionsFrame_Save", "Atr_UCConfigFrame_Save",
    "Atr_UpdateFullScanFrame",
    "Atr_deDetailsDD", "Atr_deDetailsDD_Initialize", "Atr_deDetailsDD_OnClick",
    "Atr_scanLevelDD", "Atr_scanLevelDD_Initialize", "Atr_scanLevelDD_OnClick",
    "Atr_scanLevelDD_showTip",
    "Atr_tipsShiftDD", "Atr_tipsShiftDD_Initialize", "Atr_tipsShiftDD_OnClick",
    "AuctionatorDescriptionHTML",
    "AuctionatorOption_Def_Duration_CB", "AuctionatorOption_Deftab",
    "AuctionatorOption_Deftab_Initialize", "AuctionatorOption_Deftab_OnClick",
    "AuctionatorOption_Enable_Alt_CB", "AuctionatorOption_Open_All_Bags_CB",
    "AuctionatorOption_Open_BUY_CB", "AuctionatorOption_Open_SELL_CB",
    "AuctionatorOption_Show_StartingPrice_CB",
    "AuctionatorScrollFrame", "AuctionatorSubtractFromScan", "AuctionatorVersionText",
    "BUY_TAB", "BrowseName", "CANCEL",
    "EnumerateFrames",
    "GameTooltip_OnTooltipAddMoney",
    "GetAuctionItemClasses", "GetAuctionItemSubClasses", "GetAuctionSellItemInfo",
    "GetGuildBankItemInfo", "GetGuildBankItemLink",
    "GetInboxItem", "GetInboxItemLink",
    "GetInventoryItemCount", "GetLocale",
    "GetLootRollItemInfo", "GetLootRollItemLink",
    "GetLootSlotLink", "GetMerchantItemLink",
    "GetQuestItemInfo", "GetQuestItemLink",
    "GetQuestLogChoiceInfo", "GetQuestLogItemLink",
    "GetQuestLogRewardInfo",
    "GetSendMailItem",
    "GetTradePlayerItemInfo", "GetTradePlayerItemLink",
    "GetTradeSkillItemLink", "GetTradeSkillNumMade",
    "GetTradeSkillReagentInfo", "GetTradeSkillReagentItemLink",
    "GetTradeTargetItemInfo", "GetTradeTargetItemLink",
    "GoingPrice_Allakhazam_Data", "GoingPrice_Allakhazam_SV",
    "GoingPrice_Wowhead_Data", "GoingPrice_Wowhead_SV",
    "HideInterfaceOptionsMask",
    "InterfaceOptionsFrameAddOns", "InterfaceOptionsFrameCategories",
    "ItemRefTooltip",
    "KM_ANALYZING", "KM_INQUERY", "KM_NULL_STATE", "KM_POSTQUERY",
    "KM_PREQUERY", "KM_SETTINGSORT",
    "LootLink_OnEvent", "LootSlotIsItem",
    "MoneyInputFrame_GetCopper", "MoneyInputFrame_SetCopper",
    "NO", "NumberFontNormalRight", "NumberFontNormalRightATRblue",
    "PlaySound",
    "RecipeKnown_EventScan",
    "ShowInterfaceOptionsMask",
    "SortAuctionClearSort",
    "UIDropDownMenu_CreateInfo", "UIDropDownMenu_GetSelectedValue",
    "UIDropDownMenu_JustifyText", "UIDropDownMenu_SetSelectedValue",
    "UIDropDownMenu_SetText", "UIDropDownMenu_SetWidth",
    "WOWEcon_Scan_AH", "Wowecon",
    "YES", "ZT",
    "asstr",
    "auctionator_GameTooltip_OnTooltipAddMoney",
    "event",
    "gAtr_FullScanState", "gAtr_FullScanStopReason", "gAtr_FullScanSubState",
    "gAtr_FullScanTimedOut",
    "gAtr_MeanDB", "gAtr_ScanDB",
    "gAtr_dustCacheIndex", "gAtr_ptime",
    "gCurrentPane", "gShopPane",
    "hooksecurefunc",
    "kStackList_categories",
    "num", "sd", "sortSlist",
    "tinsert", "tremove",
}

ignore = {
    "542",  -- empty if-branch (sometimes intentional in event handlers)
}
